version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 41115:41115
      - 41116:41116
      - 41116:41116/udp
      - 41118:41118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk.example.com:41117
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 41117:41117
      - 41119:41119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
