name: Nightly Build

on:
  workflow_dispatch:
  
permissions:
  contents: read
jobs:
  run-nightly-build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
